### ISSUE TITLE
deos atactk expects reads shifted bam or unshifted bam

### ISSUE THREAD

**Issue by crazyhottommy** [ParkerLab/atactk#2]
Hi,
I was reading, and got to know that one has to shift +4bp and -5bp for the reads on + and - strand for TF footprint https://sites.google.com/site/atacseqpublic/atac-seq-analysis-methods/offsetmethods

does atactk `make_cut_matrix` expects the un-shifted bam or shifted bam? http://atactk.readthedocs.io/en/latest/usage.html#creating-atac-seq-signal-plots-for-motifs.
https://github.com/GreenleafLab/NucleoATAC/issues/58

Thanks!
Tommy

**Comment by umijh** [comment]
This is controlled by the "--cut-point-offset" option. By default, it assumes the cut points are four bases from the ends of reads, resulting in the adjustment you suggest. If your BAM contains reads that have already been adjusted, you can specify "--cut-point-offset=0".

**Comment by crazyhottommy** [comment]
Thank you!

**Comment by umijh** [comment]
You're welcome.
