### ISSUE TITLE
Why create different resolutions for different fragment size "Binning"?

### ISSUE THREAD

**Issue by YichaoOU** [ParkerLab/atactk#3]
Fragment bin group | Resolution
-- | --
36-149 | 1
150-224 and 225-324 | 2
325-400 | 5

I didn't get the point. It feels that this method tends to produce higher counts around the motif boundary, and then lower counts inside the motif, which makes it like a valley.

Thanks,
Yichao

**Comment by scjparker** [comment]
The resolution is a reflection of the data density in those fragment bin groups. Based on the ATAC-seq fragment length distribution, most data will be in the 36-149bp bin and it can therefore have a higher 1bp resolution compared to the 325-400bp bin, which will have much less data.

I hope this helps.

Cheers,
Steve
